FUNC_FILL = "#dbdbdb"
SIMPLE_FILL = "#7be88b"
FUNC_STROKE = "black" #"#0b0b0b"
FUNC_MARGIN = 10
FUNC_ROUND = 3

INPORT_STROKE = FUNC_STROKE
INPORT_FILL = "#ccccdd"
OUTPORT_STROKE = FUNC_STROKE
OUTPORT_FILL = "#ddddcc"
PORT_HEIGHT = 30
PORT_MARGIN = 5

FONT_HEIGHT = PORT_HEIGHT/2
