FUNC_FILL = "#dbdbdb"
SIMPLE_FILL = "#7be88b"
FUNC_STROKE = "black" #"#0b0b0b"
FUNC_MARGIN = 12
FUNC_ROUND = 0

INPORT_STROKE = FUNC_STROKE
INPORT_FILL = "#ccccdd"
OUTPORT_STROKE = FUNC_STROKE
OUTPORT_FILL = "#ddddcc"
PORT_HEIGHT = 16
PORT_MARGIN = 1

FONT_HEIGHT = PORT_HEIGHT/1.5
